const PDFDocument = require('pdfkit');

// Builds a GST invoice / purchase voucher PDF and returns the PDFDocument stream.
// Caller is responsible for piping it to a response or file.
function generateInvoicePdf(voucher, company) {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  const isSales = voucher.type === 'SALES';
  const party = isSales ? voucher.customerId : voucher.supplierId; // populated Mongoose refs
  const title = isSales ? 'TAX INVOICE' : 'PURCHASE VOUCHER';

  doc.fontSize(18).text(company?.name || 'SmartERP', { continued: false });
  if (company?.address) doc.fontSize(9).fillColor('#555').text(company.address);
  if (company?.gstNumber) doc.fontSize(9).text(`GSTIN: ${company.gstNumber}`);
  doc.moveDown(0.5);
  doc.fillColor('#000').fontSize(14).text(title, { align: 'right' });
  doc.fontSize(10).text(`Voucher No: ${voucher.voucherNo}`, { align: 'right' });
  doc.text(`Date: ${new Date(voucher.date).toLocaleDateString('en-IN')}`, { align: 'right' });

  doc.moveDown(1);
  doc.fontSize(11).text(isSales ? 'Bill To:' : 'Supplier:', { underline: true });
  doc.fontSize(10).text(party?.name || '-');
  if (party?.address) doc.text(party.address);
  if (party?.gstNumber) doc.text(`GSTIN: ${party.gstNumber}`);
  if (party?.mobile) doc.text(`Mobile: ${party.mobile}`);

  doc.moveDown(1);

  // Table header
  const tableTop = doc.y;
  const cols = { item: 40, qty: 250, rate: 310, gst: 380, amount: 460 };
  doc.fontSize(9).fillColor('#000');
  doc.text('Item', cols.item, tableTop);
  doc.text('Qty', cols.qty, tableTop);
  doc.text('Rate', cols.rate, tableTop);
  doc.text('GST %', cols.gst, tableTop);
  doc.text('Amount', cols.amount, tableTop);
  doc.moveTo(40, tableTop + 14).lineTo(555, tableTop + 14).stroke();

  let y = tableTop + 20;
  (voucher.items || []).forEach((item) => {
    // items.stockItemId is populated into the full StockItem doc when the
    // route calls .populate('items.stockItemId')
    const name = item.stockItemId?.name || String(item.stockItemId);
    const amount = Number(item.amount) + Number(item.gstAmount);
    doc.fontSize(9);
    doc.text(name, cols.item, y, { width: 200 });
    doc.text(String(item.quantity), cols.qty, y);
    doc.text(`Rs. ${Number(item.rate).toFixed(2)}`, cols.rate, y);
    doc.text(`${Number(item.gstPercent).toFixed(2)}%`, cols.gst, y);
    doc.text(`Rs. ${amount.toFixed(2)}`, cols.amount, y);
    y += 18;
  });

  doc.moveTo(40, y + 4).lineTo(555, y + 4).stroke();
  y += 14;
  doc.fontSize(10);
  doc.text(`Sub Total: Rs. ${Number(voucher.subTotal).toFixed(2)}`, cols.rate, y, { align: 'right' });
  y += 16;
  doc.text(`GST Total: Rs. ${Number(voucher.gstTotal).toFixed(2)}`, cols.rate, y, { align: 'right' });
  y += 16;
  doc.fontSize(12).text(`Grand Total: Rs. ${Number(voucher.grandTotal).toFixed(2)}`, cols.rate, y, { align: 'right' });

  if (voucher.narration) {
    doc.moveDown(2);
    doc.fontSize(9).fillColor('#555').text(`Narration: ${voucher.narration}`);
  }

  doc.moveDown(3);
  doc.fontSize(8).fillColor('#999').text('Generated by SmartERP', 40, doc.page.height - 60);

  doc.end();
  return doc;
}

module.exports = { generateInvoicePdf };
